#!/bin/bash

echo "Commit Message: " 
read msg

git checkout master
if [ -d "docs" ]; then
  rm -r docs
fi
if [ -d "_site" ]; then
  rm -r _site
fi
git add .
git commit -m "$msg"
git push origin master
git checkout deploy
git reset --hard master
if [ -d "docs" ]; then
  rm -r docs
fi
bundle exec jekyll build
mkdir docs
cp -r _site/* docs/
git add .
git commit -m "$msg"
git push origin deploy -f


